import type { Command } from "../types";

export const navigationCommands: Command[] = [
  {
    id: "goto-home",
    name: "Home",
    description: "Go to home page",
    category: "navigation",
    keywords: ["home", "index", "main", "inicio"],
    icon: "🏠",
    action: () => ({ type: "navigate", url: "/" }),
  },
  {
    id: "goto-projects",
    name: "Projects",
    description: "View all projects",
    category: "navigation",
    keywords: ["projects", "work", "portfolio", "proyectos"],
    icon: "📦",
    action: () => ({ type: "navigate", url: "/projects" }),
  },
  {
    id: "goto-blog",
    name: "Blog",
    description: "Read blog posts",
    category: "navigation",
    keywords: ["blog", "posts", "articles", "writing"],
    icon: "📝",
    action: () => ({ type: "navigate", url: "/blog" }),
  },
  {
    id: "goto-now",
    name: "Now",
    description: "What I'm doing now",
    category: "navigation",
    keywords: ["now", "current", "today", "ahora"],
    icon: "📍",
    action: () => ({ type: "navigate", url: "/now" }),
  },
  {
    id: "goto-hire",
    name: "Hire",
    description: "Work with me",
    category: "navigation",
    keywords: ["hire", "contact", "work", "contratar"],
    icon: "💼",
    action: () => ({ type: "navigate", url: "/hire" }),
  },
  {
    id: "goto-uses",
    name: "Uses",
    description: "Tools and tech I use",
    category: "navigation",
    keywords: ["uses", "tools", "stack", "setup"],
    icon: "🛠",
    action: () => ({ type: "navigate", url: "/uses" }),
  },
  {
    id: "goto-guestbook",
    name: "Guestbook",
    description: "Sign the guestbook",
    category: "navigation",
    keywords: ["guestbook", "sign", "message", "libro"],
    icon: "📖",
    action: () => ({ type: "navigate", url: "/guestbook" }),
  },
  {
    id: "goto-terminal",
    name: "Terminal",
    description: "Interactive CLI",
    category: "navigation",
    keywords: ["terminal", "cli", "command", "shell", "consola"],
    icon: "⌨️",
    action: () => ({ type: "navigate", url: "/terminal" }),
  },
];
